Improve safety by not using temp files
`mktemp` can be vulnerable to race conditions (although on Ubuntu it is
safe). Avoid it anyway, in case it has security issues on other OSes.

Change-Id: I91eced5c03d2e10bc1d17a142d6611c2976e957d

diff --git a/bash-functions b/bash-functions
--- a/bash-functions
+++ b/bash-functions
@@ -3,17 +3,13 @@
 
 
 function chcreds() {
-    local tmpfile
-    tmpfile=$(mktemp)
-    if oscreds "$@" > "$tmpfile" 2>/dev/null; then
-        source "$tmpfile"
-        rm "$tmpfile"
-        echo "Credentials loaded for $OS_CRED"
-    else
-        rm "$tmpfile"
-        echo "Failed to load credentials"
+    local creds
+    if ! creds=$(oscreds "$@"); then
+        echo "Failed to load credentials" >&2
         return 1
     fi
+    source <(printf '%s\n' "$creds")
+    echo "Credentials loaded for $OS_CRED"
 }
 
 function recred() {
